In [1]:
import sys
from kaitoupao import *

storage dir: /Users/minkexiu/Downloads/GitHub/Tianchi_ChnAddrAnalysis
code dir: /Users/minkexiu/Documents/GitHub/Tianchi_ChnAddrAnalysis

27 17 56
先天八卦数: 1乾, 2兑, 3离, 4震, 5巽, 6坎, 7艮, 8坤
本卦上：3 本卦下：1 变爻：2

   火天大有  泽天夬  火火离
上卦  ☲离火  ☱兑金  ☲离火
下卦  ☰乾金  ☰乾金  ☲离火

03 30 10 酉时
先天八卦数: 1乾, 2兑, 3离, 4震, 5巽, 6坎, 7艮, 8坤
本卦上：3 本卦下：6 变爻：4

   火水未济 水火既济  山水蒙
上卦  ☲离火  ☵坎水  ☶艮土
下卦  ☵坎水  ☲离火  ☵坎水

# 加载数据来看看

In [2]:
import codecs

In [3]:
# 读取训练集
train_lines = codecs.open(
    create_originalData_path("train.conll")
).readlines()

In [4]:
# 读取验证集
dev_lines = codecs.open(
    create_originalData_path("dev.conll")
).readlines()

In [5]:
# 读取测试集
test_lines = codecs.open(
    create_originalData_path("final_test.txt")
).readlines()

In [6]:
# 查看训练集中的前十个字符
# 这里左侧是输入的字符，右侧是字符对应的标签  
train_lines[:20]

['浙 B-prov\n',
 '江 E-prov\n',
 '杭 B-city\n',
 '州 I-city\n',
 '市 E-city\n',
 '江 B-district\n',
 '干 I-district\n',
 '区 E-district\n',
 '九 B-town\n',
 '堡 I-town\n',
 '镇 E-town\n',
 '三 B-community\n',
 '村 I-community\n',
 '村 E-community\n',
 '一 B-poi\n',
 '区 E-poi\n',
 '\n',
 '浙 B-prov\n',
 '江 I-prov\n',
 '省 E-prov\n']

In [7]:
# 接下来我们将拼接训练集，原始训练集是对单个字符
# train_str 为训练集字符串
# train_label 为训练集对应的标签
train_str, train_label = [''], [[]]

# 从训练集文本中依次读取文本
for line in train_lines:
    # 如果训练集行中存在空格，则表示格式为 【字符 标注】
    # 将当前的字符和标注累计
    if ' ' in line:
        word, label = line.strip().split(' ')
        train_str[-1] += word
        train_label[-1].append(label)
    
    # 否则就是一个句子结束，也就是'\n'的情况
    # 新增一个空的句子和标签
    else:
        train_str.append('')
        train_label.append([])

# 输出训练集第一个样本的文本和标签
train_str[0], train_label[0]

('浙江杭州市江干区九堡镇三村村一区',
 ['B-prov',
  'E-prov',
  'B-city',
  'I-city',
  'E-city',
  'B-district',
  'I-district',
  'E-district',
  'B-town',
  'I-town',
  'E-town',
  'B-community',
  'I-community',
  'E-community',
  'B-poi',
  'E-poi'])

In [8]:
# dev_str 为验证集字符串
# dev_label 为验证集对应的标签
dev_str, dev_label = [''], [[]]

# 按照训练集标签的格式，得到验证集输入的句子和对应的标签
for line in dev_lines:

    if ' ' in line:
        word, label = line.strip().split(' ')
        dev_str[-1] += word
        dev_label[-1].append(label)
    else:
        dev_str.append('')
        dev_label.append([])

# 输出验证集第一个样本的文本和标签
dev_str[0], dev_label[0]

('杭州五洲国际', ['B-city', 'E-city', 'B-poi', 'I-poi', 'I-poi', 'E-poi'])

# 数据分析

In [9]:
# 统计字符个数
len(set(''.join(train_str)))

2307

In [10]:
from scipy.stats import describe

# 统计输入文本的长度统计值
# 最长文本长度为68，最短是3，平均长度是17
describe([
    len(x) for x in train_str
])

DescribeResult(nobs=8856, minmax=(3, 69), mean=17.157859078590786, variance=32.80534308392209, skewness=1.0429906237323388, kurtosis=2.472641491590407)

In [11]:
# 将训练集标签和验证集标签进行拼接
label_set = sum(train_label, []) + sum(dev_label, [])

# 将标签进行去重
label_set = list(set(label_set))
# label_set.insert(0, 'O')
label_set

['I-poi',
 'I-cellno',
 'S-intersection',
 'I-intersection',
 'E-distance',
 'B-prov',
 'B-community',
 'B-roadno',
 'E-assist',
 'E-city',
 'E-devzone',
 'B-subpoi',
 'B-distance',
 'E-floorno',
 'E-prov',
 'E-district',
 'B-assist',
 'I-district',
 'I-prov',
 'S-assist',
 'E-intersection',
 'E-poi',
 'I-village_group',
 'I-town',
 'E-road',
 'I-assist',
 'B-houseno',
 'S-poi',
 'I-community',
 'I-devzone',
 'S-district',
 'I-roadno',
 'B-district',
 'B-floorno',
 'E-cellno',
 'B-road',
 'O',
 'B-devzone',
 'E-community',
 'I-subpoi',
 'B-poi',
 'B-cellno',
 'E-village_group',
 'I-distance',
 'B-intersection',
 'B-village_group',
 'E-town',
 'I-floorno',
 'I-houseno',
 'I-city',
 'B-city',
 'E-roadno',
 'E-houseno',
 'E-subpoi',
 'S-community',
 'I-road',
 'B-town']

In [12]:
from collections import Counter

# 利用counter统计标签的频次
c = Counter()
c.update(sum(train_label, []))

# 按照次序倒序进行展示
c.most_common()

[('I-poi', 16657),
 ('I-road', 8095),
 ('I-roadno', 7739),
 ('B-poi', 6354),
 ('E-poi', 6354),
 ('B-district', 6124),
 ('E-district', 6124),
 ('I-district', 5842),
 ('B-road', 5711),
 ('E-road', 5711),
 ('I-town', 5270),
 ('B-city', 5118),
 ('E-city', 5118),
 ('I-city', 4262),
 ('B-prov', 4003),
 ('E-prov', 4003),
 ('B-town', 3883),
 ('E-town', 3883),
 ('B-roadno', 3716),
 ('E-roadno', 3716),
 ('I-devzone', 3714),
 ('I-prov', 3688),
 ('O', 3588),
 ('I-houseno', 2335),
 ('B-houseno', 2187),
 ('E-houseno', 2187),
 ('I-subpoi', 2018),
 ('I-community', 1708),
 ('B-community', 1571),
 ('E-community', 1571),
 ('B-subpoi', 1437),
 ('E-subpoi', 1437),
 ('B-devzone', 1020),
 ('E-devzone', 1020),
 ('B-floorno', 827),
 ('E-floorno', 827),
 ('I-cellno', 491),
 ('B-cellno', 413),
 ('E-cellno', 413),
 ('I-floorno', 357),
 ('B-assist', 228),
 ('E-assist', 228),
 ('S-assist', 187),
 ('B-village_group', 152),
 ('E-village_group', 152),
 ('B-intersection', 103),
 ('E-intersection', 103),
 ('I-village_group', 84),
 ('I-intersection', 82),
 ('I-distance', 48),
 ('B-distance', 28),
 ('E-distance', 28),
 ('S-intersection', 18),
 ('I-assist', 15),
 ('S-poi', 2)]

In [13]:
# 上述是标签的统计结果，接下来我们对标签进行编码

# 从标签编码为数值
tag_to_ix = {key: idx for idx, key in enumerate(label_set)}

# 从数值还原为标签
ix_to_tag = {idx: key for idx, key in enumerate(label_set)}

tag_to_ix['E-assist'], ix_to_tag[40]

(8, 'B-poi')

# 尝试1：LSTM实体识别

In [17]:
# 将序列进行编码
# seq 输入的序列
# to_ix 序列与标签的对应关系
def prepare_sequence(seq, to_ix):
    idxs = [to_ix[w] for w in seq]
    return torch.tensor(idxs, dtype=torch.long)

In [18]:
# 训练数据，输入文本和标签，一一对应的关系
training_data = [[list(x), y] for x, y in zip(train_str, train_label)]

In [20]:
training_data[0]

[['浙',
  '江',
  '杭',
  '州',
  '市',
  '江',
  '干',
  '区',
  '九',
  '堡',
  '镇',
  '三',
  '村',
  '村',
  '一',
  '区'],
 ['B-prov',
  'E-prov',
  'B-city',
  'I-city',
  'E-city',
  'B-district',
  'I-district',
  'E-district',
  'B-town',
  'I-town',
  'E-town',
  'B-community',
  'I-community',
  'E-community',
  'B-poi',
  'E-poi']]

In [ ]:




# 验证数据，输入文本和标签，一一对应的关系
dev_data = [[list(x), y] for x, y in zip(dev_str[:-1], dev_label[:-1])]

# 文本字符进行编码，得到字符与数值的对应的关系
word_to_ix = {}
for sent, tags in (training_data + dev_data):
    for word in sent:
        if word not in word_to_ix:
            word_to_ix[word] = len(word_to_ix)

for line in test_lines:
    line = line.strip()
    for word in line:
        if word not in word_to_ix:
            word_to_ix[word] = len(word_to_ix)