In [1]:
import sys
from kaitoupao import *

/Users/minkexiu/Documents/GitHub/Tianchi_ChnAddrAnalysis/kaitoupao.py:280: SyntaxWarning: invalid escape sequence '\d'
  *[int(x) for x in re.findall("\d+", zh_date_str)]

storage dir: /Users/minkexiu/Downloads/GitHub/Tianchi_ChnAddrAnalysis
code dir: /Users/minkexiu/Documents/GitHub/Tianchi_ChnAddrAnalysis

20 23 48
先天八卦数: 1乾, 2兑, 3离, 4震, 5巽, 6坎, 7艮, 8坤
本卦上：4 本卦下：7 变爻：6

   雷山小过 泽风大过  火山旅
上卦  ☳震木  ☱兑金  ☲离火
下卦  ☶艮土  ☴巽木  ☶艮土

03 23 1 子时
先天八卦数: 1乾, 2兑, 3离, 4震, 5巽, 6坎, 7艮, 8坤
本卦上：3 本卦下：7 变爻：1

    火山旅 泽风大过  火火离
上卦  ☲离火  ☱兑金  ☲离火
下卦  ☶艮土  ☴巽木  ☲离火

# 加载数据来看看

In [2]:
import codecs

In [3]:
# 读取训练集
train_lines = codecs.open(
    create_originalData_path("train.conll")
).readlines()

In [4]:
# 读取验证集
dev_lines = codecs.open(
    create_originalData_path("dev.conll")
).readlines()

In [5]:
# 读取测试集
test_lines = codecs.open(
    create_originalData_path("final_test.txt")
).readlines()

In [6]:
# 查看训练集中的前十个字符
# 这里左侧是输入的字符，右侧是字符对应的标签  
train_lines[:20]

['浙 B-prov\n',
 '江 E-prov\n',
 '杭 B-city\n',
 '州 I-city\n',
 '市 E-city\n',
 '江 B-district\n',
 '干 I-district\n',
 '区 E-district\n',
 '九 B-town\n',
 '堡 I-town\n',
 '镇 E-town\n',
 '三 B-community\n',
 '村 I-community\n',
 '村 E-community\n',
 '一 B-poi\n',
 '区 E-poi\n',
 '\n',
 '浙 B-prov\n',
 '江 I-prov\n',
 '省 E-prov\n']